version: '3.7'

services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    image: teste-grupo-multi-tamalu:latest
    ports:
      - '3000:3000'
    environment:
      PORT: '3000'
      POSTGRES_DB_URL: 'postgresql://postgres:postgres@db:5432/postgres'
      REDIS_HOST: 'redis'
      REDIS_PORT: '6379'
      REDIS_USERNAME: 'default'
      REDIS_PASSWORD: 'redis'
    depends_on:
      db:
        condition: service_started
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
  redis:
    image: redis:7
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass redis
